### ISSUE TITLE
一个 ip 获取微信文章内容有限制，需要限制速率或者轮换 ip。

### ISSUE THREAD

**Issue by ClericPy** [airyland/we-extract#1]
> 一个 ip 获取微信文章内容有限制，需要限制速率或者轮换 ip。

文档提到这句话, 有实际验证频率的范围么

**Comment by airyland** [comment]
大概 10s 左右吧，被屏蔽的话大概 6 个小时，限制策略一直在变化所以不大肯定。

**Comment by ClericPy** [comment]
嗯, 反爬会封整 6 小时, 目前看了下是有个检测时间点, 统计访问次数的, 没有机器学习什么的高深策略(可能也是省CPU...), 想尽可能测出临界阈值, 目前 2 秒是不安全的, 5 秒安全, 正在像中间收敛测试
