### ISSUE TITLE
图片和视频类型的文章的msg_cover应该也是可以提取到的

### ISSUE THREAD

**Issue by lijiapeng** [airyland/we-extract#2]
【图片类型】
if (type === 'image') {
          post.msg_cover = $('#img_list > img').attr('src')
        }

【视频类型】
用links.md里的视频文章去分析，可以拿到这样一个视频的缩略图地址：vpic.video.qq.com/60643382/{vid}.png，但没研究明白中间那组数字是什么，腾讯视频是把这个直接写在.txp_poster这个元素的style里的

期待更新

**Comment by airyland** [comment]
感谢建议，已支持。
