### ISSUE TITLE
大神，msg_content内容已解析不到了

### ISSUE THREAD

**Issue by liwan123123** [airyland/we-extract#3]
使用效果很好，但是有个小问题，大神，msg_content内容已解析不到了。

**Comment by airyland** [comment]
你需要给出文章 url。

**Comment by liwan123123** [comment]
https://mp.weixin.qq.com/s?__biz=MzI2NjkyNDQ3Mw==&mid=2247489204&idx=1&sn=dd97d9979fd19177e6b593813d865b8b&chksm=ea87ee62ddf06774d9ffef7369dc658c9b2c785e99149721684a8d01ec07f55e6cd336742720&scene=27#wechat_redirect
https://mp.weixin.qq.com/s?__biz=MjM5NjAwMjEwMA==&mid=2653825357&idx=1&sn=ab262c2642801d16ce47fdf62900f42b&chksm=bd3569168a42e000e41b331fc6eeb9e0e8101dca61f529a745d89d959583e0b1650ab5ce11a1&scene=27#wechat_redirect

**Comment by liwan123123** [comment]
这两条uri都取不到content，

**Comment by airyland** [comment]
测试了下，没有发现问题。你需要给出调用代码和返回结果。
![image](https://user-images.githubusercontent.com/559179/55088214-5200e000-50e6-11e9-8e80-80c5aff300ea.png)

**Comment by liwan123123** [comment]
const extract = require('.').extract
const assert = require('assert')


;(async function () {
  
  const postRs = await extract('https://mp.weixin.qq.com/s?__biz=MzAwMDM4Mjg2Nw==&mid=2650433602&idx=1&sn=020c78034ae2c145720b0c8e2f6055d0&chksm=82e70abeb59083a844faaaf9a17da0cab982f9515612738459e91438ba6e6b352e884b36737e&scene=27#wechat_redirect', {
    shouldReturnContent: false
  })

  console.log(postRs)
  })()

这是代码，执行结果
[
![11](https://user-images.githubusercontent.com/24664302/55158971-15db8700-519b-11e9-9e2f-dc95184cd9e0.jpg)
](url)

**Comment by liwan123123** [comment]
https://mp.weixin.qq.com/s?__biz=MzU2ODM5NjkzMg==&mid=2247508582&idx=1&sn=1c3b25276dab7be7c264fdc17cd349c3&chksm=fc8c7f8dcbfbf69b8d4287f57accd9ff9d67dcc70267860854a2146c0b8e918aa0f048f2afc2&scene=27#wechat_redirect试了这个网址也是content为空

**Comment by airyland** [comment]
额，你明明在调用时指定了选项 shouldReturnContent: false 。

**Comment by liwan123123** [comment]
抱歉啊，没搞明白。请问怎么用python来调用node获取结果啊

**Comment by airyland** [comment]
@liwan123123 这个我也无法解答你，理论上用 shell 来调用应该可以。
