### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by minimalistrojan** [airyland/we-extract#4]
我在小程序中调用 we-extract ，上传到腾讯云的过程中报错。说是语法错误，「 ... 」扩展运算符的问题。请问怎样解决呢？谢谢。:-)

<img width="438" alt="image" src="https://user-images.githubusercontent.com/22811809/59428380-9eb7a580-8e0f-11e9-9d48-9ebe9a5dfcaf.png">

**Comment by airyland** [comment]
可能支持 node 版本有点低。你可以发个 pr 将代码改为不用扩展符的或者自行将代码改一下试试。
