### ISSUE TITLE
1005 js 变量解析出错

### ISSUE THREAD

**Issue by lijiapeng** [airyland/we-extract#5]
上周开始，之前都正常的解析，频频出现js解析错误，此公众号之前的文章一切正常

{"done":false,"code":1005,"msg":"js 变量解析出错"}

同一公众号的示例：
示例1：https://mp.weixin.qq.com/s/UhKDRym0yMAmieXxG79Cww 一周前发表，解析正常
示例2：https://mp.weixin.qq.com/s/47eeMHTsqFNJUi_2VkDr7A 3天前发表，解析失败

**Comment by airyland** [comment]
修复了，因为微信修改了页面。

**Comment by lijiapeng** [comment]
Thanks
