### ISSUE TITLE
出现1005错误：js 变量解析出错

### ISSUE THREAD

**Issue by lvsjack** [airyland/we-extract#9]
```1005 js 变量解析出错```

最近出现了变量解析错误的情况，之前解析也都是正常的。

**Comment by airyland** [comment]
需要说明具体版本号。

**Comment by aslanTT** [comment]
> `1005 js 变量解析出错`
> 
> 最近出现了变量解析错误的情况，之前解析也都是正常的。

应该升级到最新版本就可以了。

**Comment by lvsjack** [comment]
好的，我试试，谢谢

**Comment by lvsjack** [comment]
从1.2.21升级到1.2.28后验证后没问题了
